model_bucket = "forecast-deploy-dr563105"
lambda_function_local_path = "../deployment/webservice-lambda/lambda_function.py"
docker_image_local_path = "~/Desktop/educ/mlops-zoomcamp_1/mlops-project-grocery-sales/deployment/webservice-lambda/Dockerfile" #./deployment/webservice-lambda/Dockerfile"
ecr_repo_name = "stg_forecast_ecr"
lambda_function_name = "stg_sales_forecast_lambda"
