bucket_name = "mlops-project-sales-forecast-bucket"
lambda_function_local_path = "./lambda_function.py"
docker_image_local_path = "./Dockerfile"
ecr_repo_name = "stg_ecr_forecast_image"
lambda_function_name = "stg_sales_forecast_lambda"
rest_api_name = "sales_predictor_api_tf"
