name: Continuous Integration
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: "deployment"
        run: pip install pipenv && pipenv install --dev

      - name: Run unit tests
        run: make run_tests

      - name: Run quality checks
        run: make quality-checks
